services:
  - type: web
    name: grandel-backend
    root: Backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ATLASDB_URL
        sync: false
      - key: SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false

staticSites:
  - name: grandel-frontend
    root: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: grandel-backend
          property: url